import Head from 'next/head'

const about = () => {
  return (
    <>
    <Head>
        <title>Next | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div >This is my about component about</div>
    </>
  )
}

export default about