import Head from 'next/head'

const Contact = () => {
  return (
    <>
     <Head>
        <title>Next | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div >This is my Contact page </div>
    </>
  )
}

export default Contact