import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (

  
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    {/*------- Component Level CSS  in JSX start--------- */}
      <style jsx>
        {`
        .ytube{
          color: lightblue;
        }
        `}
        </style>

        {/* global css  */}
      {/* <style jsx global>
        {`
        .ytube{
          color: lightblue;
        }
        `}
      </style> */}
    {/*----------- CSS End ------------- */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Hunter</a>
        </h1>

        <p className={styles.description}>
          Learn code form <span className='ytube'>youtube</span>  !!!!
        </p>


      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
