import Head from 'next/head'

const Login = () => {
  return (
    <>
    <Head>
        <title>Next | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div >This is my Login component -------</div>
    </>
  )
}

export default Login